wisetext/jwiser/demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import HomePageView, FormHorizontalView, FormInlineView, PaginationView, FormWithFilesView, \
    DefaultFormView, MiscView, DefaultFormsetView, DefaultFormByFieldView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^formset$', DefaultFormsetView.as_view(), name='formset_default'),
    url(r'^form$', DefaultFormView.as_view(), name='form_default'),
    url(r'^form_by_field$', DefaultFormByFieldView.as_view(), name='form_by_field'),
    url(r'^form_horizontal$', FormHorizontalView.as_view(), name='form_horizontal'),
    url(r'^form_inline$', FormInlineView.as_view(), name='form_inline'),
    url(r'^form_with_files$', FormWithFilesView.as_view(), name='form_with_files'),
    url(r'^pagination$', PaginationView.as_view(), name='pagination'),
    url(r'^misc$', MiscView.as_view(), name='misc'),
]

wisetext/jwiser/stfcrawler/urls.py
from django.conf.urls import url

from . import views
from .views import ListaAcordaosView, HomePageView

app_name = 'stfcrawler'
urlpatterns = [

    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^acordao/$', ListaAcordaosView.as_view(), name='lista'),
    url(r'^acordao/id=(?P<id_acordao>.*)/$', views.detail, name='detail'),    
    url(r'^acordao/add/$', views.acordao_add, name='acordao_add'),
]

wisetext/jwiser/stfcrawler/forms.py
from django import forms


class AddAcordaoForm(forms.Form):
	URL = forms.CharField(label='URL de Pesquisa')
	
class AcordaoForm(forms.Form):
    link_acompanhamento = forms.CharField(label='Link Acompanhamento')
    link_inteiroteor = forms.CharField(label='Link Inteiro Teor')
    arquivo_pdf = forms.CharField(label='Arquivo PDF')

    html_div = forms.CharField(label='HTML Acord&atilde;o',
        widget=forms.Textarea(),
    )
    texto_div = forms.CharField(label='Texto Acord&atilde;o',
        widget=forms.Textarea(),
    )

    

wisetext/jwiser/stfcrawler/views.py
from django.shortcuts import render
from django.template import loader
from django.http import Http404, HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.base import TemplateView
from django.contrib import messages

import os.path      
import urllib  
from urllib.error import HTTPError

from .models import Acordao
from .forms import AddAcordaoForm
from .scrapy import PaginaSTF

# Logging
import logging
logger = logging.getLogger(__name__)

# CONSTANTES
LIMITE_TENTATIVAS = 5

class ListaAcordaosView(TemplateView):
    template_name = 'stfcrawler/lista.html'

    def get_context_data(self, **kwargs):
        context = super(ListaAcordaosView, self).get_context_data(**kwargs)

        acordaos = sorted(Acordao.objects.all(), key=lambda n: (int(n.id_processo)))
        paginator = Paginator(acordaos, 50)
        page = self.request.GET.get('page')
        try:
            show_acordaos = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            show_acordaos = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            show_acordaos = paginator.page(paginator.num_pages)
        context['lista_acordaos'] = show_acordaos
        return context

class HomePageView(TemplateView):
    template_name = 'stfcrawler/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        messages.info(self.request, 'hello http://example.com')
        return context


def index(request):   
    acordaos = Acordao.objects.all()   
    acordaos.order_by('id_processo')  
    paginator = Paginator(acordaos, 50)
    page = request.GET.get('page')
    try:
        show_acordaos = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        show_acordaos = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        show_acordaos = paginator.page(paginator.num_pages)
    
    template = loader.get_template('stfcrawler/lista.html')
    context = {
        'lista_acordaos': show_acordaos,
    }
    return HttpResponse(template.render(context, request))
    
def detail(request, id_acordao):
    try:
        acordao = Acordao.objects.get(pk=id_acordao)
        existePDF = os.path.isfile(acordao.pdf_inteiro_teor)
        
        if not existePDF:
            g = urllib.request.urlopen(acordao.URL_inteiro_teor)
            arquivoPDF = "stfcrawler/pdfs/"+str(id_acordao)+".pdf"
            with open(arquivoPDF, 'b+w') as f:
                f.write(g.read())

        existePDF = os.path.isfile(acordao.pdf_inteiro_teor)
    except Acordao.DoesNotExist:
        raise Http404("Erro!")
    
    return render(request, 'stfcrawler/detail.html', {'acordao': acordao, 'existePDF':existePDF})

# Os acordaos sao adicionados por meio de uma URL de busca da jurisprudencia do STF
# Eh feita a recuperacao da página HTML da busca do site do STF e a partir dos dados
# obtidos, cada um dos acordaos é inserido na base e o arquivo PDF do seu inteiro teor
# eh baixado e armazenado localmente.
def acordao_add(request):
    # Se for uma requisicao POST, processa os dados do formulario
    if request.method == 'POST':
        # Cria um formulario e popula com os dados do request
        form = AddAcordaoForm(request.POST)
        # Checa o formulario primeiro
        if form.is_valid():                                    
            paginas = []
            url_busca = str(request.POST.get("URL", ""))
            pagina = PaginaSTF(url_busca)

            # Processa a primeira pagina
            pagina.processa_divs()            
            for acordao in pagina.acordaos:
                grava_Acordao(acordao)

            # Se tiver proximas paginas, busca-la-eias
            tentativas = 0
            while (pagina.tem_proxima()):                
                url_busca = str(pagina.prox_pagina)
                anterior = pagina
                try:
                    pagina = PaginaSTF(url_busca)
                    pagina.processa_divs()            
                    for acordao in pagina.acordaos:
                        grava_Acordao(acordao)
                except HTTPError as e:
                    if tentativas <= LIMITE_TENTATIVAS:
                        # Tenta de novo
                        pagina = anterior
                    else:
                        logger.error("Erro ao recuperar dados da pagina {0}. \
                                     Encerrando apos {1} tentativas.".format(url_busca, LIMITE_TENTATIVAS))

        return index(request)

    # se for GET (ou qualquer outro tipo) cria um form em branco
    else:        
        form = AddAcordaoForm()
        
    return render(request, 'stfcrawler/acordao_add.html', {'form': form})

# Grava um acordao na base
def grava_Acordao(acordao):
    if not (Acordao.objects.filter(id_processo=acordao["id"])):
        try:
            ac = Acordao()
            ac.id_processo = acordao["id"]
            ac.URL = acordao["link_acomp"]
            ac.URL_inteiro_teor = acordao["link_pdf"]
            ac.URL_dj_dj3 = acordao["link_dj"]
            ac.HTML_texto_basico = acordao["html"]
            ac.texto_basico = acordao["texto"]
            ac.pdf_inteiro_teor = acordao['pdf']
            dadosURL = dados_da_URL(acordao["link_acomp"])
            ac.classe = dadosURL['classe']
            ac.codigoClasse = dadosURL['codigoClasse']
            ac.recurso = dadosURL['recurso']
            ac.origem = dadosURL['origem']
            ac.tipoJulgamento = dadosURL['tipoJulgamento']
            ac.save()

            logger.info("Acordao {0} salvo com sucesso.".format(acordao["id"]))
        except:
            logger.error("Erro ao salvar dados do acordao {0}.".format(acordao["id"]))


def exibe(request, lista):    
    return render(request, 'stfcrawler/exibe.html', {'lista': lista})

# Extrai campos da URL do processo
def dados_da_URL(s):
    try:
        if not(s is None):
            campos_vals = s.split("&")[1:] # pega somente os campos extras da url
            valores = [p.split("=") for p in campos_vals]

            return ({l[0]:l[1] for l in valores})
    except:
        logger.error('Erro na extracao de dados da URL!')
        return None

wisetext/jwiser/stfcrawler/templates/stfcrawler/acordao_add.html
{% extends 'stfcrawler/base.html' %}

{% load bootstrap3 %}

{% block title %}
    Inserir Grupos de Acord&atilde;os
{% endblock %}

{% block content %}
    <!--div id="progress">Recuperando ac&oacute;rd&acute;os...</div-->

    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
    </form>

{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/base.html
{% extends 'stfcrawler/bootstrap.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
    <div class="container">
        <h1>{% block title %}(no title){% endblock %}</h1>        
       <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">jWiser</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">                    
                    <li><a href="{% url 'stfcrawler:lista' %}">Ac&oacute;rd&atilde;os<span class="sr-only">(current)</span></a></li>                    
		<li><a href="{% url 'stfcrawler:acordao_add' %}">Add Ac&oacute;rd&atilde;os</a></li>
                </ul>

            </div>
        </div>
        </nav>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/detail.html
{% extends 'stfcrawler/base.html' %}
{% load bootstrap3 %}
{% block title %}{% endblock %}
{% block content %}
<h3>Processo n&ordm;: {{ acordao.id_processo }}</h3>
<table class="table">	    
	<tr><td><a href="{{ acordao.URL }}">Acompanhamento Processual</a></td></tr>
	<tr><td><a href="{{ acordao.URL_inteiro_teor }}">Link Inteiro Teor</a></td></tr>
	<tr><td><strong>Arquivo PDF: </strong>{{ acordao.pdf_inteiro_teor }}
	<tr><td><strong>Arquivo TXT: </strong>{{ acordao.txt_inteiro_teor }}
    {% if not existePDF %}
        {% bootstrap_alert "Arquivo PDF não encontrado! Recupere o acórdão novamento do site do STF."  alert_type='danger' %}
    {% endif %}</td></tr>                                       
	<tr><td><strong>Dados Acord&atilde;o</strong><br/><textarea rows="20" cols="150">{{ acordao.texto_basico }}</textarea></td></tr>
	<tr><td><strong>Criado em: </strong>{{ acordao.criado_em }}
	<tr><td><strong>Alterado em: </strong>{{ acordao.alterado_em }}
</table>
{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/exibe.html
{% extends 'stfcrawler/base.html' %}

{% block content %}
<ul>
    {% for item in lista %}        
        <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/home.html
{% extends 'stfcrawler/base.html' %}
{% load bootstrap3 %}

{% block title %}{% endblock %}

{% block content %}
    <strong>Django jWiser Livre</strong>.
{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/index.html
{% extends 'stfcrawler/base.html' %}

{% block content %}
{% if lista_acordaos %}
    <ul>
    {% for acordao in lista_acordaos %}        
        <li><a href="{% url 'stfcrawler:detail' acordao.id_processo %}">{{ acordao.id_processo }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/lista.html
{% extends 'stfcrawler/base.html' %}

{% load bootstrap3 %}

{% block title %}
    Ac&oacute;rd&atilde;os
{% endblock %}

{% block content %}
    {% if lista_acordaos %}	
	    <table class="table">
	    {% for acordao in lista_acordaos %}        		
		<tr>
			<td><a href="{% url 'stfcrawler:detail' acordao.id_processo %}">Processo n&ordm; {{ acordao.id_processo }}</a></td>
		</tr>
	    {% endfor %}
	    </table>
    {% else %}
            <p>No polls are available.</p>
    {% endif %}
    <hr>

    {% bootstrap_pagination lista_acordaos url="/stfcrawler/acordao?page=1" size="large" %}

{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/oldacordao_add.html
{% extends 'stfcrawler/base.html' %}
{% block title %}Inserir Grupos de Acord&atilde;os{% endblock %}
{% block content %}    
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form }}
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
{% endblock %}

wisetext/jwiser/stfcrawler/templates/stfcrawler/teste.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{# Display a form #}
<form action="/url/to/submit/" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Submit
    </button>
  {% endbuttons %}
</form>

{# Read the documentation for more information #}